name: Testing

on: push

jobs:
  test_project:
    runs-on: unbuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Django unit tests
      run-on: |
        pip3 install --user Django
        python3 manage.py test
